### ISSUE TITLE
Typo in extension method

### ISSUE THREAD

**Issue by kevinrenskers** [magyarosibotond/AttributedStringTag#1]
`applyintAttributesForTag` instead of `applyingAttributesForTag`.

Nice library by the way!

**Comment by magyarosibotond** [comment]
Hey @kevinrenskers!

Thanks for filing the issue. I've managed to fix the type on #2 and migrated the project to Swift 5.1. I  also gave you maintainer access to file issues / improvements while using the app.  

There's a new version available through Cocoapods and Swift PM.

Thanks for the contribution!
